config/routes.rb
Blocipedia::Application.routes.draw do

  devise_for  :users,
              controllers: { registrations: "my_devise/registrations" }
  resources :users, only: [:show, :update]
  resources :pages do
    resources :references
    resources :invites
  end

  resources :charges, only: [:new, :create]
  post 'stripehook' => 'subscriptions#hook'

  get 'about' => "welcome#about"
  root to: 'welcome#index'
  
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <div class="row">
    <h1 class="text-center">Blocipedia</h1>
    <p class="lead text-center">Create and share markdown wikis</p>
    <p class="text-center"><%= link_to "Sign up", new_user_registration_path, class: 'btn btn-primary btn-lg' %></p>
  </div>
</div>
<div>
  <div class="row">
    <div class="col-md-4 col-md-offset-2">
      <h4 class="text-center">Create as many public wikis as you want!</h4><br>
      <p class="text-center"><%= link_to "Free Plan", new_user_registration_path, class: 'btn btn-primary btn-lg' %></p>
    </div>
    <div class="col-md-4">
      <h4 class="text-center">Create private wikis!</h4><br>
      <p class="text-center"><%= link_to "Premium Plan", new_charge_path, class: 'btn btn-primary btn-lg' %></p>
    </div>
  </div>
</div> 