config/routes.rb
Blocipedia::Application.routes.draw do

  devise_for  :users,
              controllers: { registrations: "my_devise/registrations" }
  resources :users, only: [:show, :update]
  resources :pages do
    resources :references
    resources :invites
  end

  resources :charges, only: [:new, :create]
  post 'stripehook' => 'subscriptions#hook'

  get 'about' => "welcome#about"
  root to: 'welcome#index'
  
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocipedia", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Pages", pages_path %></li>
        <% if current_user %>
          <li><%= link_to "My wikis", user_path(current_user.id) %></li>
        <% end %>

        <div class="pull-right user-info">
          <% if current_user %>
            Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>.
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>

      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type ="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>

    </div>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Blocipedia</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>
<body>
      <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocipedia", root_path %></li>
        <li><%= link_to "About", about_path %></li>

        <div class="pull-right user-info">
          <% if current_user %>
            Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>.
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>

      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type ="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>


  <%= yield %>
</body>
</html>